"""initial schema

Revision ID: f3180a7f18db
Revises: -
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f3180a7f18db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("reply_to_email", sa.String(length=320), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("accent_color", sa.String(length=7), nullable=False),
        sa.Column("greeting_text", sa.Text(), nullable=True),
        sa.Column("farewell_text", sa.Text(), nullable=True),
        sa.Column("email_variant", sa.String(length=32), nullable=True),
        sa.Column("send_delay_hours", sa.Integer(), nullable=True),
        sa.Column("min_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("magic_link_token_hash", sa.String(length=64), nullable=True),
        sa.Column("magic_link_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accent_color ~ '^#[0-9a-fA-F]{6}$'", name=op.f("ck_creators_accent_color_is_hex")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creators")),
        sa.UniqueConstraint("slug", name=op.f("uq_creators_slug")),
    )
    op.create_table(
        "job_runs",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_job_runs")),
    )
    op.create_table(
        "subscribers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_reason", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "blocked_reason IN ('bounce', 'complaint')",
            name=op.f("ck_subscribers_blocked_reason_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscribers")),
        sa.UniqueConstraint("email", name=op.f("uq_subscribers_email")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("oauth_refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("oauth_granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("oauth_needs_reconsent", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('youtube')", name=op.f("ck_sources_kind_valid")),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["creators.id"], name=op.f("fk_sources_creator_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("kind", "external_id", name=op.f("uq_sources_kind_external_id")),
    )
    op.create_index(op.f("ix_sources_creator_id"), "sources", ["creator_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confirm_token", sa.String(length=64), nullable=True),
        sa.Column("confirm_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirm_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribe_token", sa.String(length=64), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'unsubscribed')",
            name=op.f("ck_subscriptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
            name=op.f("fk_subscriptions_creator_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["subscribers.id"],
            name=op.f("fk_subscriptions_subscriber_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("confirm_token", name=op.f("uq_subscriptions_confirm_token")),
        sa.UniqueConstraint(
            "subscriber_id", "creator_id", name=op.f("uq_subscriptions_subscriber_id_creator_id")
        ),
        sa.UniqueConstraint("unsubscribe_token", name=op.f("uq_subscriptions_unsubscribe_token")),
    )
    op.create_index(
        op.f("ix_subscriptions_creator_id"), "subscriptions", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_subscriber_id"), "subscriptions", ["subscriber_id"], unique=False
    )
    op.create_table(
        "appearances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("is_backfill", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("view_token", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "official_captions_declined", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('detected', 'enriched', 'transcribed', 'analyzed', 'skipped_short', 'skipped_no_transcript', 'skipped_too_long', 'unavailable', 'failed')",
            name=op.f("ck_appearances_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_appearances_source_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appearances")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_appearances_source_id_external_id")
        ),
        sa.UniqueConstraint("view_token", name=op.f("uq_appearances_view_token")),
    )
    op.create_index(op.f("ix_appearances_source_id"), "appearances", ["source_id"], unique=False)
    op.create_index(op.f("ix_appearances_status"), "appearances", ["status"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appearance_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('summary', 'sentiment')", name=op.f("ck_analyses_kind_valid")),
        sa.ForeignKeyConstraint(
            ["appearance_id"],
            ["appearances.id"],
            name=op.f("fk_analyses_appearance_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
        sa.UniqueConstraint("appearance_id", "kind", name=op.f("uq_analyses_appearance_id_kind")),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("appearance_id", sa.Integer(), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("tokens_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_cents", sa.Numeric(precision=12, scale=4), server_default="0", nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appearance_id"],
            ["appearances.id"],
            name=op.f("fk_llm_calls_appearance_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
            name=op.f("fk_llm_calls_creator_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(op.f("ix_llm_calls_creator_id"), "llm_calls", ["creator_id"], unique=False)
    op.create_table(
        "mailings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appearance_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop_token", sa.String(length=64), nullable=False),
        sa.Column("preview_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("render_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recipient_count", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'sentiment_ready', 'preview_sent', 'sending', 'sent', 'stopped', 'cancelled', 'failed')",
            name=op.f("ck_mailings_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["appearance_id"],
            ["appearances.id"],
            name=op.f("fk_mailings_appearance_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailings")),
        sa.UniqueConstraint("appearance_id", name=op.f("uq_mailings_appearance_id")),
        sa.UniqueConstraint("stop_token", name=op.f("uq_mailings_stop_token")),
    )
    op.create_index(op.f("ix_mailings_send_at"), "mailings", ["send_at"], unique=False)
    op.create_index(op.f("ix_mailings_status"), "mailings", ["status"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appearance_id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("is_generated", sa.Boolean(), nullable=False),
        sa.Column("segments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('youtube_official', 'youtube_unofficial')",
            name=op.f("ck_transcripts_origin_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["appearance_id"],
            ["appearances.id"],
            name=op.f("fk_transcripts_appearance_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
        sa.UniqueConstraint("appearance_id", name=op.f("uq_transcripts_appearance_id")),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mailing_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["mailing_id"],
            ["mailings.id"],
            name=op.f("fk_deliveries_mailing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_deliveries_subscription_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint(
            "mailing_id", "subscription_id", name=op.f("uq_deliveries_mailing_id_subscription_id")
        ),
    )
    op.create_index(op.f("ix_deliveries_mailing_id"), "deliveries", ["mailing_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_mailing_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_table("transcripts")
    op.drop_index(op.f("ix_mailings_status"), table_name="mailings")
    op.drop_index(op.f("ix_mailings_send_at"), table_name="mailings")
    op.drop_table("mailings")
    op.drop_index(op.f("ix_llm_calls_creator_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_appearances_status"), table_name="appearances")
    op.drop_index(op.f("ix_appearances_source_id"), table_name="appearances")
    op.drop_table("appearances")
    op.drop_index(op.f("ix_subscriptions_subscriber_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_creator_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_sources_creator_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("subscribers")
    op.drop_table("job_runs")
    op.drop_table("creators")
    # ### end Alembic commands ###
